# Generated by Django 2.2.1 on 2019-05-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
    ]
