# Generated by Django 2.2.1 on 2019-05-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190518_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userinfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
