# Generated by Django 2.2.1 on 2019-05-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_info',
            table='book_info',
        ),
    ]
