# Generated by Django 2.2.1 on 2019-05-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190518_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bookinfo',
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='book_info',
        ),
    ]
